
// This file has been generated by the GUI designer. Do not modify.
namespace NabuAdaptorLinux
{
	public partial class DisplaySettings
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label3;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Entry txtbaudRate;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.CheckButton chkSave;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.CheckButton chkFlowControl;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget NabuAdaptorLinux.DisplaySettings
			this.Name = "NabuAdaptorLinux.DisplaySettings";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource("NabuAdaptorLinux.nabu.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(2));
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child NabuAdaptorLinux.DisplaySettings.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.HeightRequest = 40;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.HeightRequest = 0;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("BaudRate (Default is 11865):");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w2.Y = 5;
			this.hbox1.Add(this.fixed1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.HeightRequest = 40;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtbaudRate = new global::Gtk.Entry();
			this.txtbaudRate.WidthRequest = 295;
			this.txtbaudRate.CanFocus = true;
			this.txtbaudRate.Name = "txtbaudRate";
			this.txtbaudRate.IsEditable = true;
			this.txtbaudRate.InvisibleChar = '•';
			this.fixed2.Add(this.txtbaudRate);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtbaudRate]));
			w4.X = 100;
			this.hbox1.Add(this.fixed2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.fixed2]));
			w5.Position = 1;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.HeightRequest = 40;
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.chkSave = new global::Gtk.CheckButton();
			this.chkSave.CanFocus = true;
			this.chkSave.Name = "chkSave";
			this.chkSave.Label = global::Mono.Unix.Catalog.GetString("Save Settings on Exit");
			this.chkSave.Active = true;
			this.chkSave.DrawIndicator = true;
			this.chkSave.UseUnderline = true;
			this.fixed4.Add(this.chkSave);
			this.hbox2.Add(this.fixed4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed4]));
			w8.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.hbox2.Add(this.fixed5);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.fixed5]));
			w9.Position = 1;
			this.vbox2.Add(this.hbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.hbox3.Add(this.fixed6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.fixed6]));
			w11.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox3.Add(this.fixed3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.fixed3]));
			w12.Position = 1;
			this.vbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.chkFlowControl = new global::Gtk.CheckButton();
			this.chkFlowControl.CanFocus = true;
			this.chkFlowControl.Name = "chkFlowControl";
			this.chkFlowControl.Label = global::Mono.Unix.Catalog.GetString("Disable Flow Control");
			this.chkFlowControl.DrawIndicator = true;
			this.chkFlowControl.UseUnderline = true;
			this.vbox2.Add(this.chkFlowControl);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.chkFlowControl]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Internal child NabuAdaptorLinux.DisplaySettings.ActionArea
			global::Gtk.HButtonBox w16 = this.ActionArea;
			w16.Name = "dialog1_ActionArea";
			w16.Spacing = 10;
			w16.BorderWidth = ((uint)(5));
			w16.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16[this.buttonCancel]));
			w17.Expand = false;
			w17.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16[this.buttonOk]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 622;
			this.DefaultHeight = 185;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
